### ISSUE TITLE
All-ranking evaluation

### ISSUE THREAD

**Issue by MeycL** [ICharlotteI/DHMAE#1]
It seems that the current evaluation method is still sampling-based. In the code (https://github.com/ICharlotteI/DHMAE/blob/main/model.py#L288-L308), item_inputs are still needed to obtain the final representation. How can I modify it to use an all-ranking evaluation method? Thank you very much for your reply.

**Comment by ICharlotteI** [comment]
Thank you for your issue.  However, I do not fully understand your point. The current code employs an all-ranking protocol while still requiring _item_inputs_. Notably, _item_inputs_ are derived from [https://github.com/ICharlotteI/DHMAE/blob/main/datautil.py#L33-L42](https://github.com/ICharlotteI/DHMAE/blob/main/datautil.py#L33-L42) (i.e., the candidate items are the users' all uninteracted items), unlike the previous sampling evaluation. If you need to compute the ratings of all users for all items, you can calculate them directly using _self.user_embedding.weight_ and _self.item_embedding.weight_.

**Comment by MeycL** [comment]
Thank you for your prompt response. It may be my limited understanding, but I interpret the all-ranking method as ranking all items for a batch of users, similar to an [example](https://github.com/RUCAIBox/RecBole/blob/master/recbole/model/general_recommender/lightgcn.py#L200-L210) in RecBole. Could you please clarify the difference between the two?

**Comment by ICharlotteI** [comment]
I follow the definition of the all-ranking protocol in **LightGCN** (see **LightGCN: Simplifying and Powering Graph Convolution Network for Recommendation**, Section 4.1), which states that "_The evaluation metrics are recall@20 and ndcg@20 computed by the all-ranking protocol all items that are not interacted by a user are the candidates._" I have a cursory reading in RecBole, the authors calculate the score of a batch user for all items, but later in the evaluation phase the test items **may be** selected based on the id. If scores on all items are considered, then the items interacted with in the training set will definitely have a higher top ranking.

**Comment by MeycL** [comment]
Thank you for your reply, I understand.
