### ISSUE TITLE
Building the MovieLens Dataset

### ISSUE THREAD

**Issue by MeycL** [ICharlotteI/DHMAE#2]
Thank you very much for your excellent work. I would like to ask if it would be possible to provide information on how to construct the MovieLens dataset? I would like to try it on other datasets, and I would greatly appreciate any help you can provide.

**Comment by ICharlotteI** [comment]
Thanks for your appreciation. For MovieLens dataset, we are referring to the paper **Group recommendations with rank aggregation and collaborative filtering** about _random groups_, based on the traditional user recommendation datasets that do not involve direct group relationships. The process includes loading user interaction data, removing interactions with ratings less than 3 (or not removing), randomly selecting group sizes in a specified range, merging the co-interaction items of members, discarding the group if the number of co- interactions among members is less than a threshold (or not considering it, in which case the group cold-start is a bit severe), treating the items of the members' co- interactions as the items being interacted with by the group, and selecting the last interaction of the group as the test set ( or randomized). In this MovieLens dataset construction, we do not remove users' interactions and do not take into account the number of common interactions between members, and we divide the test set by randomly selecting interactions. If you can, please leave your email and I will explain further.

**Comment by MeycL** [comment]
Thank you for your detailed explanation. Here is my email: [greenghost7@163.com](mailto:greenghost7@163.com). If it’s convenient, could you please send me a copy of the data processing code? I would like to experiment with it on other datasets. Thank you very much!

**Comment by ICharlotteI** [comment]
I have replied to you by email.
